version=0.1
[default.deploy.parameters]
stack_name = "pavimentados-serverless-dev"
s3_bucket = "project-deployment-templates"
s3_prefix = "pavimentados"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Mode=dev InfraTableName=infra-dev UserPoolId=us-east-1_<random> AttachmentsBucketName=infra-attachments-dev DatalakeBucketName=infra-datalake-dev ArtifactsBucketName=infra-artifacts-dev"

[prod.deploy.parameters]
stack_name = "pavimentados-serverless"
s3_bucket = "project-deployment-templates"
s3_prefix = "pavimentados"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Mode=prod InfraTableName=infra UserPoolId=us-east-1_<random> AttachmentsBucketName=infra-attachments DatalakeBucketName=infra-datalake ArtifactsBucketName=infra-artifacts"
