AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Infra serverless core resources

Parameters:
  SesIdentityDomain:
    Type: String
    Description: SES identity domain to send emails.
    Default: ''
  Mode:
    Type: String
    Description: Environment context
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Mappings:
  ModeMap:
    dev:
      ModeSuffix: -dev
    test:
      ModeSuffix: -test
    prod:
      ModeSuffix: ''

Conditions:
  HasSesDomain: !Not [!Equals [!Ref SesIdentityDomain, '']]

Resources:
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    Properties:
      BucketName: !Sub
        - 'infra-artifacts${envSuffix}-${AWS::AccountId}'
        - envSuffix: !FindInMap [ModeMap, !Ref Mode, ModeSuffix]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Product
          Value: Infra
        - Key: Environment
          Value: !Ref Mode
        - Key: Name
          Value: ArtifactsBucket

  DatalakeBucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    Properties:
      BucketName: !Sub
        - 'infra-datalake${envSuffix}-${AWS::AccountId}'
        - envSuffix: !FindInMap [ModeMap, !Ref Mode, ModeSuffix]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Product
          Value: Infra
        - Key: Environment
          Value: !Ref Mode
        - Key: Name
          Value: DatalakeBucket

  AttachmentsBucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    Properties:
      BucketName: !Sub
        - 'infra-attachments${envSuffix}-${AWS::AccountId}'
        - envSuffix: !FindInMap [ModeMap, !Ref Mode, ModeSuffix]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - HEAD
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
              - ETag
            MaxAge: 3000
      Tags:
        - Key: Product
          Value: Infra
        - Key: Environment
          Value: !Ref Mode
        - Key: Name
          Value: AttachmentsBucket

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - 'infra${suffix}'
        - suffix: !FindInMap [ModeMap, !Ref Mode, ModeSuffix]
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - 
          AttributeName: Pk
          AttributeType: S
        - 
          AttributeName: Sk
          AttributeType: S
        - 
          AttributeName: Gsi1Pk
          AttributeType: S
      KeySchema:
        - 
          AttributeName: Pk
          KeyType: HASH
        - 
          AttributeName: Sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - 
          IndexName: gsi1
          KeySchema:
            - 
              AttributeName: Gsi1Pk
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Product
          Value: Infra
        - Key: Environment
          Value: !Ref Mode
        - Key: Name
          Value: DbTable

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub
        - 'infra-user-pool${suffix}'
        - suffix: !FindInMap [ModeMap, !Ref Mode, ModeSuffix]
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: !If [HasSesDomain, DEVELOPER, COGNITO_DEFAULT]
        SourceArn: !If
          - HasSesDomain
          - !Sub 'arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${SesIdentityDomain}'
          - !Ref AWS::NoValue
        From: !If
          - HasSesDomain
          - !Sub 'noreply@${SesIdentityDomain}'
          - !Ref AWS::NoValue
      MfaConfiguration: 'OFF'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true
          RequireSymbols: true
          RequireLowercase: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 30
      Schema:
        - Name: given_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
      LambdaConfig:
        CustomMessage: !GetAtt UserPoolCustomizeMessageFunction.Arn
      UserPoolTags:
        Product: Infra
        Environment: !Ref Mode
        Name: UserPool

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Domain: !Sub
        - 'infra-user-pool${suffix}-${stackReference}'
        - suffix: !FindInMap [ModeMap, !Ref Mode, ModeSuffix]
          stackReference: !Select [ 4, !Split [ '-', !Select [ 2, !Split [ '/', !Ref AWS::StackId ] ] ] ]

  UserPoolCustomizeMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub
        - 'infra-user-pool-customize-message${envSuffix}'
        - envSuffix: !FindInMap [ModeMap, !Ref Mode, ModeSuffix]
      Description: Customize UserPool messages sent to users
      Handler: index.lambda_handler
      Timeout: 30
      MemorySize: 128
      Runtime: python3.11
      Policies:
        - AWSLambdaBasicExecutionRole
      InlineCode: |
        DEFAULT_APP_NAME = 'InfraCore'
        DEFAULT_URL = 'https://infradinamica.org'

        INVITATION_SUBJECT_TEMPLATE = 'Bienvenido a {app_name}'
        INVITATION_MESSAGE_TEMPLATE = '''<html>
          <body>
            <p>
              Hola {username_parameter},
              <br /><br />
              Te invitamos a la aplicación <b>{app_name}</b>.<br />
              Tu usuario de acceso a infra-core es <b>{username_parameter}</b> y la contraseña temporal es <b>{code_parameter}</b><br />
              puedes acceder mediante el siguiente vínculo: <a href="{url}">{app_name}</a>
              <br /><br />
              Saludos!
            </p>
          </body>
        </html>'''


        def lambda_handler(event, context):
            if event['triggerSource'] == 'CustomMessage_AdminCreateUser':
                event['response']['emailSubject'] = INVITATION_SUBJECT_TEMPLATE.format(
                    app_name=event['request'].get('clientMetadata', {}).get('app_name', DEFAULT_APP_NAME)
                )

                event['response']['emailMessage'] = INVITATION_MESSAGE_TEMPLATE.format(
                    username_parameter=event['request']['usernameParameter'],
                    code_parameter=event['request']['codeParameter'],
                    app_name=event['request'].get('clientMetadata', {}).get('app_name', DEFAULT_APP_NAME),
                    url=event['request'].get('clientMetadata', {}).get('url', DEFAULT_URL)
                )

            return event
    Tags:
      Product: Infra
      Environment: !Ref Mode
      Name: UserPoolCustomizeMessageFunction

  CognitoUserPoolLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      FunctionName: !Ref UserPoolCustomizeMessageFunction
      SourceArn: !GetAtt CognitoUserPool.Arn

Outputs:
  TableName:
    Description: DynamoDB table name
    Value: !Ref DynamoDBTable
  AttachmentsBucketName:
    Description: Attachments bucket name
    Value: !Ref AttachmentsBucket
  DatalakeBucketName:
    Description: Datalake bucket name
    Value: !Ref DatalakeBucket
  ArtifactsBucketName:
    Description: Artifacts bucket name
    Value: !Ref ArtifactsBucket
  UserPoolId:
    Description: Cognito user pool id
    Value: !Ref CognitoUserPool
  UserPoolDomain:
    Description: Cognito user pool domain
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
